// <auto-generated />
using System;
using Biblioteca.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20260926032946_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Domain.Entities.Autores.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Autores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Nacionalidad = "Colombiana",
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Nacionalidad = "Estadounidense",
                            Nombre = "Robert C. Martin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Nacionalidad = "Estadounidense",
                            Nombre = "Eric Evans"
                        });
                });

            modelBuilder.Entity("Biblioteca.Domain.Entities.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Descripcion = "Obras de ficción narrativa",
                            Nombre = "Novela"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Descripcion = "Diseño y construcción de software",
                            Nombre = "Ingeniería de Software"
                        });
                });

            modelBuilder.Entity("Biblioteca.Domain.Entities.Libros.Libro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Libros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AnioPublicacion = 1967,
                            AutorId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CategoriaId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Isbn = "9780307474728",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AnioPublicacion = 1985,
                            AutorId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CategoriaId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Isbn = "9780307387264",
                            Titulo = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AnioPublicacion = 2017,
                            AutorId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CategoriaId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Isbn = "9780134494166",
                            Titulo = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AnioPublicacion = 2003,
                            AutorId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CategoriaId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Isbn = "9780321125217",
                            Titulo = "Domain-Driven Design"
                        });
                });

            modelBuilder.Entity("Biblioteca.Domain.Entities.Libros.Libro", b =>
                {
                    b.HasOne("Biblioteca.Domain.Entities.Autores.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Domain.Entities.Categorias.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
